GET http://localhost:5000/users/try HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhcyI6eyJfaWQiOiI2NzA4NjBkMTg2ZWJjMjhhODZlODM2YTQiLCJ1c2VybmFtZSI6InNhYmJhaCIsInBhc3N3b3JkIjoiJDJhJDEwJFZZTTluLnN3dk5jZ3guSlVRTHg3V2VWMHkzNWFaNGFQTVA1QWh4cXpIR3gyREwuN1VLaUNhIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xMFQyMzoxODo0MS41ODFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xMFQyMzoxODo0MS41ODFaIiwiX192IjowfSwiaWF0IjoxNzI4NjcyNzkxfQ.VGZkXFDBTR0zUAd0yEfaNDvYFieMOm4pkZjxcCusubA

###

POST http://localhost:5000/users/reg HTTP/1.1
Content-Type: application/json

{
    "username": "SABBAH",
    "password": "1234567"
}

###


POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "sabbah",
    "password": "1234567"
}

###
GET http://localhost:5000 HTTP/1.1
###
GET http://localhost:5000/users/670860d186ebc28a86e836a4 HTTP/1.1